version: 0.2

env:
  parameter-store:
    AWS_ACCESS_KEY_ID: /codebuild/AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: /codebuild/AWS_SECRET_ACCESS_KEY
    AWS_ACCOUNT_ID: /codebuild/AWS_ACCOUNT_ID 
phases:
  install: 
    commands:
      - docker --version
      - echo docker installed
      - echo "setting up iam user credentials"
      - bash configure-named-profile.sh
      - echo "installing eksctl cli"
      - bash eks/scripts/eksctl-install.sh
      - aws --version
      - eksctl --version
  pre_build:
    commands:
      - echo logging in Docker hub
      - login docker
      # - echo $AWS_DEFAULT_REGION
      # - aws ecr get-login-password | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com
      # - echo building images 
      - echo "connecting to charity cluster"
      - make update-config
      - kubectl get all
  build:
    commands:
      - echo build started on `date`
      - echo "deploying pods and services for charity"
      - bash deployment-orchastrator.sh
      - bash create-record-53.sh
      - echo build finished on `date`