version: 0.2

env:
  parameter-store:
    AWS_ACCESS_KEY_ID: /codebuild/AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: /codebuild/AWS_SECRET_ACCESS_KEY
    AWS_ACCOUNT_ID: /codebuild/AWS_ACCOUNT_ID 
    PROFILE_NAME: /codebuild/PROFILE_NAME
    DOCKER_TOKEN: /codebuild/DOCKER_TOKEN
    DOCKER_USERNAME: /codebuild/DOCKER_USERNAME
phases:
  install: 
    commands:
      - echo "setting up iam user credentials"
      - bash configure-named-profile.sh
  pre_build:
    commands:
      # - echo building and pushing image to docker hub
      # - bash push-image.sh
      - echo "connecting to charity cluster"
      - make update-config
      - kubectl get all
  build:
    commands:
      - echo build started on `date`
      - echo "putting the application down"
      - bash uninstalling-k8s-orchastrator.sh
      - bash delete-record-53.sh
      - echo build finished on `date`