---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: charity-webapp
spec:
  selector:
    matchLabels:
      app: charity-webapp
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: charity-webapp
    spec:
      containers:
      - name: charity
        image: hirodaridevdock/charity-website-image:4.0